### ISSUE TITLE
feat: Create page layouts for root index and area detail

### ISSUE THREAD

**Issue by trentgillis** [trentgillis/prime-condies#28]
- Create the root layout and root index layouts
- @media responsiveness, see Figmas

**Comment by Philip-A-R** [comment]
Hey @trentgillis  I think I can tackle this, do you think so?

**Comment by Philip-A-R** [comment]
This may have been over my head 😂 I got started and though I understand some of the input I think this would be a long process! I might follow along with this to see how you do it, but I think it would take a super long time for me to do.
