### ISSUE TITLE
feat: implement header (nav) component

### ISSUE THREAD

**Issue by trentgillis** [trentgillis/prime-condies#29]
- Implement header component based on the figmas

**Comment by Philip-A-R** [comment]
@trentgillis Hey! will you shoot me over the figma? Also - you just want this in vanilla CSS yeah?

**Comment by Philip-A-R** [comment]
`import React from 'react'
import styled from 'styled-components';

const HeaderWrapper = styled.main`
 height: 130px;
  display: flex;
  flex-wrap: wrap;
  align-items: space-around;
`;
const LogoWrapper = styled.main`
  display: flex;
  height: 36px;
  width: 152px
  align-items: left;
`;
const SearchWrapper = styled.main`
  display: flex;
  height: 46px;
width: 100%;
justify-content: center;
flex-grow: 1;

`;

function Header() {
  return (
    <HeaderWrapper>
      <LogoWrapper>
        <img src="/logo.svg" alt="" />
      </LogoWrapper>
      <SearchWrapper>
        <input type="text" placeholder='Search' />
      </SearchWrapper>
    </HeaderWrapper>
  )
}

export default Header

`
